### ISSUE TITLE
stanza version needs to be specified in requirements.txt (1.4.0)

### ISSUE THREAD

**Issue by DSLituiev** [ncbi/GNorm2#3]
The README says that stanza version must be 1.4.0, but this is not reflected in `requirements.txt`, which leads to the latest version installed (1.7.0 as of today), and an error:

```
Traceback (most recent call last):
  File "/home/dlituiev/GNorm2/GeneNER_SpeAss_run.py", line 25, in <module>
    nlp_token = stanza.Pipeline(model_dir='gnorm_trained_models/stanza', lang='en', processors={'tokenize': 'spacy'},package='None', download_method=None) #package='craft' ;./gnorm_trained_models/stanza
  File "/home/dlituiev/GNorm2/gnorm2/lib64/python3.9/site-packages/stanza/pipeline/core.py", line 237, in __init__
    self.load_list = maintain_processor_list(resources, lang, package, processors, maybe_add_mwt=(not kwargs.get("tokenize_pretokenized")))
  File "/home/dlituiev/GNorm2/gnorm2/lib64/python3.9/site-packages/stanza/resources/common.py", line 208, in maintain_processor_list
    add_mwt(processors, resources, lang)
  File "/home/dlituiev/GNorm2/gnorm2/lib64/python3.9/site-packages/stanza/resources/common.py", line 184, in add_mwt
    if value in resources[lang][PACKAGES] and MWT in resources[lang][PACKAGES][value]:
KeyError: 'packages'
```

There may be a simple fix to this, but I am not familiar with stanza

**Comment by DSLituiev** [comment]
similarly with the latest `transformers` (unconstrained in requirements), one gets:
```
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/dlituiev/GNorm2/GeneNER_SpeAss_run.py", line 716, in <module>
    speciesAss(args.NERoutpath,args.SAoutpath, args.SAmodel)
  File "/home/dlituiev/GNorm2/GeneNER_SpeAss_run.py", line 623, in speciesAss
    nn_model.load_model(modelfile)
  File "/home/dlituiev/GNorm2/src_python/SpeAss/model_sa.py", line 103, in load_model
    self.model.load_weights(model_file)
  File "/home/dlituiev/GNorm2/gnorm2/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/dlituiev/GNorm2/gnorm2/lib64/python3.9/site-packages/keras/src/backend.py", line 4359, in _assign_value_to_variable
    variable.assign(value)
ValueError: Cannot assign value to variable ' tf_bert_model_1/bert/embeddings/word_embeddings/weight:0': Shape mismatch.The variable shape (32774, 512), and the assigned value shape (2, 512) are incompatible.
Total 0 file(s) wait(s) for process.
```

**Comment by ChihHsuanWei** [comment]
Hi, GNorm2 somehow has a difficultly within Python 3.9. we prepared the requirments.txt for python 3.8 and 3.10. Could you please reinstall the appropriate lib? Let me know if any further issue?

[requirements-py38.txt](https://github.com/ncbi/GNorm2/blob/main/requirements-py38.txt)
[requirements-py38.txt](https://github.com/ncbi/GNorm2/blob/main/requirements-py310.txt)

Thanks. Wei
