### ISSUE TITLE
 if value in resources[lang][PACKAGES] and MWT in resources[lang][PACKAGES][value]: KeyError: 'packages'

### ISSUE THREAD

**Issue by xiongsircool** [ncbi/GNorm2#8]
I encountered an error while executing the following command:
```
./GNorm2.sh input output
```
Error message:
```
Traceback (most recent call last):
  File "/home/xxy/sd8T/Arabidopsis_porject/mutant_actrial/GNorm2_modle/GeneNER_SpeAss_run.py", line 25, in <module>
    nlp_token = stanza.Pipeline(model_dir='gnorm_trained_models/stanza', lang='en', processors={'tokenize': 'spacy'},package='None', download_method=None) #package='craft'; ./gnorm_trained_models/stanza
  File "/home/xxy/miniforge3/envs/python39/lib/python3.9/site-packages/stanza/pipeline/core.py", line 235, in __init__
    self.load_list = maintain_processor_list(resources, lang, package, processors, maybe_add_mwt=(not kwargs.get("tokenize_pretokenized")))
  File "/home/xxy/miniforge3/envs/python39/lib/python3.9/site-packages/stanza/resources/common.py", line 208, in maintain_processor_list
    add_mwt(processors, resources, lang)
  File "/home/xxy/miniforge3/envs/python39/lib/python3.9/site-packages/stanza/resources/common.py", line 184, in add_mwt
    if value in resources[lang][PACKAGES] and MWT in resources[lang][PACKAGES][value]:
KeyError: 'packages'
Total 0 file(s) wait(s) for process.
```

Despite following your guidelines, I still encounter errors that prevent the system from starting properly. I suspect the error is due to an inability to correctly read the `resources.json` file within the provided Stanza model directory. Can I replace your provided models directly by downloading standard models using `stanza.download("en")`? It appears from the documentation that there have been no specific adjustments made to these models.
For reference, I am using Stanza version 1.6.1 with Python 3.9.
![image](https://github.com/ncbi/GNorm2/assets/45034344/580ce258-e957-42a3-8941-61914f4ba993)
![image](https://github.com/ncbi/GNorm2/assets/45034344/a0856cb8-0c5a-4f31-af89-eb73ea10354a)

**Comment by xiongsircool** [comment]
I have resolved this issue. It turns out that the software runs correctly when based on Python 3.8. Switching to this version of Python eliminated the problem.

**Comment by xiongsircool** [comment]
1
